### PR TITLE
feat: add linglong.yaml file

### PR DESCRIPTION
**Pull request by wjyrich**

### CODE REVIEW

**Comment by wjyrich** [comment]
image

**Comment by myml** [comment]
x86 layer文件下载 https://ci.deepin.com/repo/obs/linglong:/app:/CI:/amd64:/linglongdev:/io.github.SerialPortAssistant:/PR-1/deepin_23_repo/

**Comment by myml** [comment]
以下内容为自动生成: 

[x86 layer 文件下载](https://ci.deepin.com/repo/obs/linglong:/app:/CI:/amd64:/linglongdev:/io.github.SerialPortAssistant:/PR-1/deepin_23_repo/)

**Comment by myml** [comment]
| 架构 | 构建状态 |
| --- | --- |
| x86 | [build result](https://ci.deepin.com/repo/obs/linglong:/app:/CI:/amd64:/linglongdev:/io.github.SerialPortAssistant:/PR-1/deepin_23_repo/) |

在构建成功后可点击状态图片下载 layer 文件, 使用 ll-cli install xxx_binary.layer 安装测试

⚠️ 为减少存储占用, 构建文件仅在PR打开时有效

**Pull request merged**
